### ISSUE TITLE
Erro de digitação no slide

### ISSUE THREAD

**Issue by hlcanhette** [cleitonbueno/arduinoday#1]
Bom dia Cleiton.

É um erro bobo na linha de comando que está no slide.

Está escrito: $ pip install -r requeriments.txt
e o correto seria:  $ pip install -r requirements.txt

Att, Henrique Lagamba Canhette

**Comment by cleitonbueno** [comment]
Excelente observação, erro bobo assim como erro em código quem desenvolve não percebe. Obrigado pela correção, já estou subindo junto com outras correções.
